<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="3" ignored="5" total="12" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="49007" started-at="2018-09-03T12:27:18Z" finished-at="2018-09-03T12:28:07Z">
    <groups>
    </groups>
    <test name="Addmembershiptoorg" duration-ms="20714" started-at="2018-09-03T12:27:18Z" finished-at="2018-09-03T12:27:38Z">
      <class name="Com.NF.NetForumScenarious.VerifyOrganization">
        <test-method status="SKIP" signature="verifyAddOrganization(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.VerifyOrganization@49c43f4e]" name="verifyAddOrganization" duration-ms="1" started-at="2018-09-03T17:57:38Z" depends-on-methods="Com.NF.NetForumScenarious.Addorganization.AddRotaryOrganization" finished-at="2018-09-03T17:57:38Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VerifyOrganization.verifyAddOrganization(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.VerifyOrganization@49c43f4e] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VerifyOrganization.verifyAddOrganization(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.VerifyOrganization@49c43f4e] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddOrganization -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.VerifyOrganization@49c43f4e]" name="endTest" is-config="true" duration-ms="212" started-at="2018-09-03T17:57:38Z" finished-at="2018-09-03T17:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Com.NF.NetForumScenarious.VerifyOrganization -->
      <class name="Com.NF.NetForumScenarious.AddRelatedorganization">
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.AddRelatedorganization@69a10787]" name="endTest" is-config="true" duration-ms="169" started-at="2018-09-03T17:57:38Z" finished-at="2018-09-03T17:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="SKIP" signature="AssignClubtoDistrict(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.AddRelatedorganization@69a10787]" name="AssignClubtoDistrict" duration-ms="0" started-at="2018-09-03T17:57:38Z" depends-on-methods="Com.NF.NetForumScenarious.AddOrgMembership.addorgmembership" finished-at="2018-09-03T17:57:38Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AddRelatedorganization.AssignClubtoDistrict(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.AddRelatedorganization@69a10787] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AddRelatedorganization.AssignClubtoDistrict(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.AddRelatedorganization@69a10787] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AssignClubtoDistrict -->
      </class> <!-- Com.NF.NetForumScenarious.AddRelatedorganization -->
      <class name="Com.NF.NetForumScenarious.AddOrgMembership">
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.AddOrgMembership@12028586]" name="endTest" is-config="true" duration-ms="154" started-at="2018-09-03T17:57:38Z" finished-at="2018-09-03T17:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="SKIP" signature="addorgmembership(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.AddOrgMembership@12028586]" name="addorgmembership" duration-ms="0" started-at="2018-09-03T17:57:38Z" depends-on-methods="Com.NF.NetForumScenarious.VerifyOrganization.verifyAddOrganization" finished-at="2018-09-03T17:57:38Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method AddOrgMembership.addorgmembership(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.AddOrgMembership@12028586] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method AddOrgMembership.addorgmembership(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.AddOrgMembership@12028586] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addorgmembership -->
      </class> <!-- Com.NF.NetForumScenarious.AddOrgMembership -->
      <class name="Com.NF.NetForumScenarious.LaunchandLoginintoNF15">
        <test-method status="PASS" signature="setenvironmentInof()[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@d6da883]" name="setenvironmentInof" is-config="true" duration-ms="15" started-at="2018-09-03T17:57:18Z" finished-at="2018-09-03T17:57:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setenvironmentInof -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@d6da883]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-09-03T17:57:18Z" finished-at="2018-09-03T17:57:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Com.NF.NetForumScenarious.LaunchandLoginintoNF15.LaunchApplication(java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LaunchApplication(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@d6da883]" name="LaunchApplication" duration-ms="18704" started-at="2018-09-03T17:57:18Z" finished-at="2018-09-03T17:57:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[C:\\NetforumUpgradeInMaven\\NetforumUpgrade\\NF_Input.xlsx,LaunchNF]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Com.NF.NetForumScenarious.LaunchandLoginintoNF15.execute(LaunchandLoginintoNF15.java:120)
	at Com.NF.NetForumScenarious.LaunchandLoginintoNF15.LaunchApplication(LaunchandLoginintoNF15.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@d6da883]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-09-03T17:57:37Z" finished-at="2018-09-03T17:57:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LaunchApplication status=FAILURE method=LaunchandLoginintoNF15.LaunchApplication(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@d6da883] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@d6da883]" name="endTest" is-config="true" duration-ms="1055" started-at="2018-09-03T17:57:37Z" finished-at="2018-09-03T17:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Com.NF.NetForumScenarious.LaunchandLoginintoNF15 -->
      <class name="Com.NF.NetForumScenarious.Addorganization">
        <test-method status="SKIP" signature="AddRotaryOrganization(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.Addorganization@45afc369]" name="AddRotaryOrganization" duration-ms="0" started-at="2018-09-03T17:57:38Z" depends-on-methods="Com.NF.NetForumScenarious.LaunchandLoginintoNF15.LaunchApplication" finished-at="2018-09-03T17:57:38Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Addorganization.AddRotaryOrganization(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.Addorganization@45afc369] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Addorganization.AddRotaryOrganization(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.Addorganization@45afc369] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddRotaryOrganization -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.Addorganization@45afc369]" name="endTest" is-config="true" duration-ms="341" started-at="2018-09-03T17:57:38Z" finished-at="2018-09-03T17:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Com.NF.NetForumScenarious.Addorganization -->
    </test> <!-- Addmembershiptoorg -->
    <test name="FindOrganizationbyexcelfile" duration-ms="28108" started-at="2018-09-03T12:27:39Z" finished-at="2018-09-03T12:28:07Z">
      <class name="Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue">
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue@25359ed8]" name="beforeMethod" is-config="true" duration-ms="1" started-at="2018-09-03T17:57:52Z" finished-at="2018-09-03T17:57:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue.findorgbyexcelvalues(java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="findorgbyexcelvalues(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue@25359ed8]" name="findorgbyexcelvalues" duration-ms="14611" started-at="2018-09-03T17:57:52Z" finished-at="2018-09-03T17:58:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[C:\\NetforumUpgradeInMaven\\NetforumUpgrade\\NF_Input.xlsx,FIndOrgStoreValue]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue.execute(fFindOrganizationbyexcelvalue.java:80)
	at Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue.findorgbyexcelvalues(fFindOrganizationbyexcelvalue.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findorgbyexcelvalues -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue@25359ed8]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-09-03T17:58:07Z" finished-at="2018-09-03T17:58:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=findorgbyexcelvalues status=FAILURE method=fFindOrganizationbyexcelvalue.findorgbyexcelvalues(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue@25359ed8] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue@25359ed8]" name="endTest" is-config="true" duration-ms="253" started-at="2018-09-03T17:58:07Z" finished-at="2018-09-03T17:58:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Com.NF.NetForumScenarious.fFindOrganizationbyexcelvalue -->
      <class name="Com.NF.NetForumScenarious.LaunchandLoginintoNF15">
        <test-method status="PASS" signature="setenvironmentInof()[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@37574691]" name="setenvironmentInof" is-config="true" duration-ms="0" started-at="2018-09-03T17:57:39Z" finished-at="2018-09-03T17:57:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setenvironmentInof -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@37574691]" name="beforeMethod" is-config="true" duration-ms="0" started-at="2018-09-03T17:57:39Z" finished-at="2018-09-03T17:57:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void Com.NF.NetForumScenarious.LaunchandLoginintoNF15.LaunchApplication(java.lang.String) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="LaunchApplication(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@37574691]" name="LaunchApplication" duration-ms="13007" started-at="2018-09-03T17:57:39Z" finished-at="2018-09-03T17:57:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[C:\\NetforumUpgradeInMaven\\NetforumUpgrade\\NF_Input.xlsx,LaunchNF]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at Com.NF.NetForumScenarious.LaunchandLoginintoNF15.execute(LaunchandLoginintoNF15.java:120)
	at Com.NF.NetForumScenarious.LaunchandLoginintoNF15.LaunchApplication(LaunchandLoginintoNF15.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@37574691]" name="afterMethod" is-config="true" duration-ms="0" started-at="2018-09-03T17:57:52Z" finished-at="2018-09-03T17:57:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LaunchApplication status=FAILURE method=LaunchandLoginintoNF15.LaunchApplication(java.lang.String)[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@37574691] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:Com.NF.NetForumScenarious.LaunchandLoginintoNF15@37574691]" name="endTest" is-config="true" duration-ms="216" started-at="2018-09-03T17:57:52Z" finished-at="2018-09-03T17:57:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
      </class> <!-- Com.NF.NetForumScenarious.LaunchandLoginintoNF15 -->
    </test> <!-- FindOrganizationbyexcelfile -->
  </suite> <!-- Suite1 -->
</testng-results>
